pipeline {
    agent any
    tools {
	maven 'apache-maven-3.5.4'
	jdk 'jdk1.8.0_144.jdk'
    }
    stages {
	stage('Initialize') {
		steps {
			sh '''
				echo "PATH = ${PATH}"
                    		echo "M2_HOME = ${M2_HOME}"
                	''' 
		}
	}
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
